### ISSUE TITLE
Coordination des collections

### ISSUE THREAD

**Issue by samszo** [samszo/gestedit#1]
Est-ce que les auteurs peuvent coordonner une collection en français mais pas en anglais ou l'inverse ?

**Comment by ISTE-Ludo** [comment]
Il est possible d'être coordo d'une collection/série en anglais uniquement. Sans équivalent francais (car nous ne traduisons (generalement pas de l anglais vers le francais, sauf cas particuliers), donc si tous les ouvrages arrivent en anglais la collection n existera pas en francais)

En revanche, le francais amène toujours à l'anglais
