### ISSUE TITLE
tri par date

### ISSUE THREAD

**Issue by ISTE-Ludo** [samszo/gestedit#34]
peux-tu stp ajouter un tri avec les dates suivantes (exemple) :
date arrivée prévue du manuscrit
date prévue de remise de traduction
date prévue de parution FR
date prévue de parution GB
date de parution définitive

**Comment by samszo** [comment]
OK j'ajoute la fonctionnalité...

**Comment by samszo** [comment]
j'ai ajouté les critères de date dans le moteur de recherche
