### ISSUE TITLE
planning du livre

### ISSUE THREAD

**Issue by ISTE-Ludo** [samszo/gestedit#35]
Si on ajoute une tâche dans un ouvrage, cette tâche devrait s'afficher pour les autres ouvrages

**Comment by samszo** [comment]
OK je modifie...

**Comment by samszo** [comment]
si on ajoute la tâche au niveau d'un livre (onglet livre ou production), elle s'ajoute uniquement à cet ouvrage et aux nouveaux
si on ajoute la tâche au niveau des paramètres (onglet paramètre), elle s'ajoute à tous les ouvrages même les anciens

**Comment by samszo** [comment]
l'ajout de tâche se fait uniquement dans l'onglet paramètre
