### ISSUE TITLE
optoin d'affichage des auteurs par livre

### ISSUE THREAD

**Issue by ISTE-Ludo** [samszo/gestedit#47]
dans le futur, nous allons avoir de gros ouvrages multi-auteurs (avec droits d'auteurs)
ex : un titre avec 120 auteurs differents...
question : comme nous ne voulons que voir les principaux auteurs dans l'onglet "auteurs" de la page d'accueil. Est-possible de prévoir une case "afficher le nom" à coté du nom d'un auteur dans : contrats/contrat d'auteur

**Comment by samszo** [comment]
oui pourquoi pas mais pour le même besoin j'utiliserai plutôt un rôle particulier par exemple : auteur secondaire
dans l'onglet auteurs vous pourrais filtrer par rôle et n'afficher que ceux qui vous intéresse

**Comment by samszo** [comment]
réglé avec ordre couvertue
