### ISSUE TITLE
Traitement champs onglet BD dans Global

### ISSUE THREAD

**Issue by samszo** [samszo/gestedit#6]
Il faudrait une description des champs suivants :
- Traduction prév. 6,50 (GBP)
- OKS prév. 2,57 (GBP)
- Relecture prév. 1,27 (GBP)
- OKS prév. 0,34 (GBP)

**Comment by ISTE-Ludo** [comment]
Ce sont des couts par page des sous traitants. Il faut que nous discutions au tel de cet aspect "compta prévisionnelle"/"couts de fabrication" qui n'est pas une priorité pour la base pour l'instant.
